- name: Import dump WordPress DB
  community.mysql.mysql_db:
    login_host: "{{ db_host }}"
    login_port: "{{ db_master_port }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    name: "{{ db_name }}"
    state: import
    target: "{{ db_dump_path }}"

- name: Delete dump file
  ansible.builtin.file:
    path: "{{ db_dump_path }}"
    state: absent

- name: WordPress container start
  docker_container:
    name: wordpress
    state: started

- name: Get replication status
  community.mysql.mysql_replication:
    mode: getreplica
    login_host: "{{ db_host }}"
    login_port: "{{ db_slave_port }}"
    login_user: root
    login_password: "{{ db_slave_password }}"
  register: slave_status  

- name: Show replication status
  debug:
    msg: |
      Slave_IO_Running: {{ slave_status.Slave_IO_Running }}
      Slave_SQL_Running: {{ slave_status.Slave_SQL_Running }}
      Seconds_Behind_Master: {{ slave_status.Seconds_Behind_Master }}

- name: Display Configuration Variables
  ansible.builtin.debug:
    msg:
      - "wordpress: True" # True or False
      - "wordpress_port: 80" # 80 or 8080 or whatewer
      - "wordpress_db_name: {{ db_name }}" # WP database name
      - "db_master: mysql" # container name
      - "db_replica: mysql_slave" # container name
      - "db_pass: {{ db_password }}" # root password for master and replica
